### ISSUE TITLE
Few tags are missing

### ISSUE THREAD

**Issue by bishtgautam** [NGEET/fates-release#9]
Rob noticed that the latest integration of FATES in https://github.com/E3SM-Project/E3SM/commit/3bdbfdb37cf1f1107762c57f77aaa79aba6ee80c
is missing the correct tag. e.g. FATES bea1fb1 should be tagged as `sci.1.12.1_api.3.1.0` to be 
consistent with the developer version.

**Comment by bishtgautam** [comment]
After a bit more digging, it appears that all tags of FATES are correctly marked in this repo. The issue seems to be with the submodule of FATES in E3SM.

```
git clone git@github.com:E3SM-Project/E3SM
cd E3SM
git submodule update --init
git submodule status
 bea1fb10c4840a727d82c8cdb431590e0e4b7d30 components/clm/src/external_models/fates (sci.1.0.0_api.1.0.0-455-gbea1fb10)
 38e0b0461ce10da7de809b752bacc70860ae8bbd components/clm/src/external_models/mpp (v0.0.1-74-g38e0b04)
 f2cbe748addb922c3df55835ae75d7204be9ffda components/clm/src/external_models/sbetr (alm-betr-v2.0-2-gf2cbe74)
 ece5f71aa623e75cf9b35151b37a124b8402922c components/mpas-source (v6.0)
```

**Comment by rgknox** [comment]
Thanks for investigating @bishtgautam
